[package]
name = "near-lake-framework"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2021"
rust-version = "1.58.1"

[dependencies]
aws-config = "0.6.0"
aws-endpoint = "0.6.0"
aws-sdk-s3 = "0.6.0"
aws-smithy-http = "0.36.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.55"
tokio = { version = "1.1", features = ["sync", "time"] }
tokio-stream = { version = "0.1" }
tracing = "0.1.13"
tracing-subscriber = "0.2.4"

near-indexer-primitives = { git = "https://github.com/near/nearcore", rev = "bd8a2de708b0350046eb16ce398a7ec896a94f0c" }
